### PR TITLE
Memleak

### PR DESCRIPTION
**Pull request by xboi209**
Fixed various memory leaks #152

### CODE REVIEW

**Comment by xboi209** [comment]
This pull request also fixes #160 by closing the eventlog file stream when the Windows GUI exits instead of on server shutdown because the file stream is still used after shutdown if compiled with Windows GUI.

**Comment by xboi209** [comment]
See #165 first before accepting pull request

**Comment by xboi209** [comment]
At this commit, PvPGN leaks 4KB of memory every few seconds.

**Comment by HarpyWar** [comment]
Please, explain the case in which occurs that "PvPGN leaks 4KB of memory every few seconds." (with or without users, any commands execution, when idle)? Does it leak more KB per a second before this commit?

What's about this comment https://github.com/HarpyWar/pvpgn/pull/164#commitcomment-12692593

**Comment by xboi209** [comment]
>Please, explain the case in which occurs that "PvPGN leaks 4KB of memory every few seconds." (with or without users, any commands execution, when idle)?
When PvPGN is idle with no users, it leaks 4KB every few seconds.

>Does it leak more KB per a second before this commit?
Yes, it leaked a lot more before.

>What's about this comment #164 (comment)
Fixed in commit 85965c7804f915aa1905656e7fb5ea8fbf37b225

**Comment by HarpyWar** [comment]
I told about this https://github.com/xboi209/pvpgn/commit/9a5be8f44591639517729bac18965189596d156c#commitcomment-12692593

To make this pull request can be successfully compiled in Linux, cmake files must be updated with g++, right?  (now gcc used)

**Comment by xboi209** [comment]
>I told about this xboi209@9a5be8f#commitcomment-12692593

That's fine

>To make this pull request can be successfully compiled in Linux, cmake files must be updated with g++, right? (now gcc used)
Travis seems to be using g++ already, you need to configure travis to add the C++14 flag.

**Pull request merged**
