### PR TITLE
Fix User DC when click Tournament Icon & Set user to Default Icon when I...

### PR DESCRIPTION
**Pull request by aancw**
...CON SWITCH HACK

Signed-off-by: aancw <cacaddv@gmail.com>

### CODE REVIEW

**Comment by HarpyWar** [comment]
Could you please provide patch with only clean changes that relates to your fix? I see many unnecessary code changes without any sense.
Thanks.

**Comment by HarpyWar** [comment]
Thanks. Also please, provide reproduction steps to see what was wrong before your fix.

**Comment by aancw** [comment]
Change from previous step only make the code better clean. Bug fixing when i click tournament icon because tournament icon is not listed and i got DCed when default icon is clicked so we need to change from NULL icon to 1O3W (Default Icon code ). I dont know why my user with legal icon got DCed too and the pvpgn say that user is icon switch hack. So only change user icon to default when user use illegal w3lh.dll and not kill session

**Comment by HarpyWar** [comment]
AppVeyor (Windows) build failed. What's wrong?

**Comment by aancw** [comment]
I dont know, but i think it's from AppVeyor with missing Microsoft.Cpp.Default.props and that error say this :

c:\builder\build\ZERO_CHECK.vcxproj(27,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by HarpyWar** [comment]
That was a false alarm. 
Now it succeed in the latest commit without related changes.

**Pull request merged**
